-- Create table for Store Requests
create table if not exists store_requests (
  id bigint generated by default as identity primary key,
  barcode text not null,
  product_name text,
  qty integer default 1,
  status text default 'pending', -- pending, accepted, completed, rejected
  request_by text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS)
alter table store_requests enable row level security;

-- Create policies (assuming public access for simplicity in this tool, but should be restricted in prod)
create policy "Enable all access for all users" on store_requests for all using (true) with check (true);

-- Create a realtime publication so the frontend can receive updates immediately
alter publication supabase_realtime add table store_requests;
