-- Create a specific table for tracking NEW items added to inventory
create table if not exists added_items_log (
  id bigint generated by default as identity primary key,
  barcode text not null,
  item_name text not null,
  qty integer not null default 0,
  added_by text not null, -- The user who added the item
  location text, -- Which Excel sheet/Location it was added to
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table added_items_log enable row level security;

-- Create policy for public access (simpler for internal tool)
create policy "Enable all access for all users" on added_items_log for all using (true) with check (true);

-- Realtime subscription
alter publication supabase_realtime add table added_items_log;
