const fs = require('fs');

const code = [
"import React, { useState, useRef, useEffect } from 'react';",
"import ReactMarkdown from 'react-markdown';",
"import remarkGfm from 'remark-gfm';",
"import { MessageSquare, X, Send, Sparkles, LayoutDashboard, Paperclip, FileText, Volume2, VolumeX, User, Plus, Sun, Moon, Trash2 } from 'lucide-react';",
"import { useLanguage } from '../../contexts/LanguageContext';",
"import { supabase } from '../../utils/supabaseClient';",
"",
"const BOT_NAME = 'Joi';",
"const DEEPSEEK_API_KEY = import.meta.env.VITE_DEEPSEEK_API_KEY || '';",
"",
"const getMd = (dark) => ({",
"  h1: ({children}) => <h1 className={'text-xl font-bold mt-4 mb-2 ' + (dark?'text-white':'text-gray-900')}>{children}</h1>,",
"  h2: ({children}) => <h2 className={'text-lg font-bold mt-3 mb-1 ' + (dark?'text-white':'text-gray-800')}>{children}</h2>,",
"  h3: ({children}) => <h3 className={'text-base font-semibold mt-2 mb-1 ' + (dark?'text-gray-200':'text-gray-700')}>{children}</h3>,",
"  p: ({children}) => <p className='mb-3 leading-7 last:mb-0'>{children}</p>,",
"  strong: ({children}) => <strong className={'font-semibold ' + (dark?'text-white':'text-gray-900')}>{children}</strong>,",
"  ul: ({children}) => <ul className='list-disc pl-5 mb-3 space-y-1'>{children}</ul>,",
"  ol: ({children}) => <ol className='list-decimal pl-5 mb-3 space-y-1'>{children}</ol>,",
"  li: ({children}) => <li className='leading-7'>{children}</li>,",
"  code: ({inline, children}) => inline",
"    ? <code className={'px-1.5 py-0.5 rounded text-xs font-mono ' + (dark?'bg-white/10 text-blue-300':'bg-gray-100 text-blue-600')}>{children}</code>",
"    : <pre className={'p-4 rounded-xl overflow-x-auto text-xs font-mono my-3 border ' + (dark?'bg-black/40 text-green-300 border-white/10':'bg-gray-900 text-green-400 border-gray-700')}><code>{children}</code></pre>,",
"  table: ({children}) => <div className={'overflow-x-auto my-4 rounded-xl border ' + (dark?'border-white/10':'border-gray-200')}><table className='w-full text-sm border-collapse'>{children}</table></div>,",
"  thead: ({children}) => <thead className={dark?'bg-white/5 border-b border-white/10':'bg-gray-50 border-b border-gray-200'}>{children}</thead>,",
"  th: ({children}) => <th className={'px-4 py-3 text-left font-semibold text-xs uppercase tracking-wider ' + (dark?'text-white/70':'text-gray-500')}>{children}</th>,",
"  td: ({children}) => <td className={'px-4 py-3 border-b ' + (dark?'text-white/80 border-white/5':'text-gray-700 border-gray-100')}>{children}</td>,",
"  tr: ({children}) => <tr className={'transition-colors ' + (dark?'hover:bg-white/5':'hover:bg-gray-50')}>{children}</tr>,",
"  a: ({href, children}) => <a href={href} target='_blank' rel='noreferrer' className='text-blue-400 underline'>{children}</a>,",
"});",
"",
"const AIChatBot = ({ onBack }) => {",
"  const [messages, setMessages] = useState([]);",
"  const [input, setInput] = useState('');",
"  const [isLoading, setIsLoading] = useState(false);",
"  const [chatHistory, setChatHistory] = useState([]);",
"  const [currentChatId, setCurrentChatId] = useState(null);",
"  const [isSidebarOpen, setIsSidebarOpen] = useState(false);",
"  const [attachedFile, setAttachedFile] = useState(null);",
"  const [imagePreview, setImagePreview] = useState(null);",
"  const [isTTSEnabled, setIsTTSEnabled] = useState(true);",
"  const [isDark, setIsDark] = useState(true);",
"  const messagesEndRef = useRef(null);",
"  const textareaRef = useRef(null);",
"  const { language } = useLanguage();",
"",
"  const toggleTTS = () => { window.speechSynthesis.cancel(); setIsTTSEnabled(p => !p); };",
"",
"  useEffect(() => {",
"    const saved = localStorage.getItem('joah_ai_history');",
"    if (saved) setChatHistory(JSON.parse(saved));",
"  }, []);",
"",
"  useEffect(() => {",
"    if (chatHistory.length > 0) localStorage.setItem('joah_ai_history', JSON.stringify(chatHistory));",
"  }, [chatHistory]);",
"",
"  useEffect(() => { messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' }); }, [messages, isLoading]);",
"",
"  const startNewChat = () => {",
"    const nc = { id: Date.now().toString(), title: 'New chat', messages: [] };",
"    setChatHistory(p => [nc, ...p]);",
"    setCurrentChatId(nc.id);",
"    setMessages([]);",
"  };",
"",
"  const loadChat = (chat) => { setCurrentChatId(chat.id); setMessages(chat.messages || []); };",
"",
"  const deleteChat = (e, id) => {",
"    e.stopPropagation();",
"    setChatHistory(p => p.filter(c => c.id !== id));",
"    if (currentChatId === id) { setMessages([]); setCurrentChatId(null); }",
"  };",
"",
"  const fetchStock = async (barcode) => {",
"    try { const { data, error } = await supabase.from('store_inventory').select('*').eq('barcode', barcode).single(); return error ? 'Not found' : JSON.stringify(data); }",
"    catch (e) { return 'Error: ' + e.message; }",
"  };",
"",
"  const fetchDailyRequests = async () => {",
"    try {",
"      const today = new Date().toISOString().split('T')[0];",
"      const { data, error } = await supabase.from('store_requests').select('id,doc_no,store_name,product_name,barcode,qty,unit,status,created_at,approved_by,stock_at_request').gte('created_at', today + 'T00:00:00').lte('created_at', today + 'T23:59:59').order('created_at', { ascending: false });",
"      return error ? 'Error: ' + error.message : (data.length ? JSON.stringify(data) : 'No requests today.');",
"    } catch (e) { return 'Error: ' + e.message; }",
"  };",
"",
"  const fetchHistory = async (barcode, fromDate, toDate) => {",
"    try {",
"      let q = supabase.from('store_requests').select('*').eq('barcode', barcode);",
"      if (fromDate) q = q.gte('created_at', fromDate);",
"      else { const d = new Date(); d.setDate(d.getDate() - 90); q = q.gte('created_at', d.toISOString()); }",
"      if (toDate) q = q.lte('created_at', toDate);",
"      const { data, error } = await q.order('created_at', { ascending: false });",
"      return error ? 'Error: ' + error.message : (data.length ? JSON.stringify(data) : 'No history found.');",
"    } catch (e) { return 'Error: ' + e.message; }",
"  };",
"",
"  const handleFileChange = (e) => {",
"    const file = e.target.files[0];",
"    if (!file) return;",
"    setAttachedFile(file);",
"    if (file.type.startsWith('image/')) { const r = new FileReader(); r.onload = ev => setImagePreview(ev.target.result); r.readAsDataURL(file); }",
"  };",
"",
"  const handleSend = async () => {",
"    if (!input.trim() && !attachedFile) return;",
"    let chatId = currentChatId;",
"    if (!chatId) { const nc = { id: Date.now().toString(), title: input.substring(0, 30), messages: [] }; setChatHistory(p => [nc, ...p]); setCurrentChatId(nc.id); chatId = nc.id; }",
"    const userMsg = { role: 'user', content: input, hasFile: !!attachedFile, fileName: attachedFile?.name };",
"    const newMsgs = [...messages, userMsg];",
"    setMessages(newMsgs);",
"    setInput(''); setAttachedFile(null); setImagePreview(null); setIsLoading(true);",
"    try {",
"      const apiMsgs = [{ role: 'system', content: 'You are Joi, an AI inventory agent. TOOL DATA IS LAW. Never rename products or hallucinate. Always show barcodes. Format data as markdown tables. Language: ' + (language === 'la' ? 'Lao' : 'Thai') + '.' }, ...newMsgs];",
"      let done = false, finalMsg = null;",
"      while (!done) {",
"        const res = await fetch('https://api.deepseek.com/v1/chat/completions', { method: 'POST', headers: { 'Content-Type': 'application/json', 'Authorization': 'Bearer ' + DEEPSEEK_API_KEY }, body: JSON.stringify({ model: 'deepseek-chat', messages: apiMsgs, tools: [{ type: 'function', function: { name: 'check_stock_by_barcode', description: 'Get stock by barcode', parameters: { type: 'object', properties: { barcode: { type: 'string' } }, required: ['barcode'] } } }, { type: 'function', function: { name: 'get_daily_requests', description: 'Get all store requests for today' } }, { type: 'function', function: { name: 'get_request_history_by_barcode', description: 'Get historical requests by barcode', parameters: { type: 'object', properties: { barcode: { type: 'string' }, from_date: { type: 'string' }, to_date: { type: 'string' } }, required: ['barcode'] } } }], tool_choice: 'auto' }) });",
"        const d = await res.json();",
"        const msg = d.choices[0].message;",
"        if (msg.tool_calls) {",
"          apiMsgs.push(msg);",
"          for (const tc of msg.tool_calls) {",
"            const args = JSON.parse(tc.function.arguments || '{}');",
"            let content;",
"            if (tc.function.name === 'check_stock_by_barcode') content = await fetchStock(args.barcode);",
"            else if (tc.function.name === 'get_daily_requests') content = await fetchDailyRequests();",
"            else if (tc.function.name === 'get_request_history_by_barcode') content = await fetchHistory(args.barcode, args.from_date, args.to_date);",
"            else content = 'Unknown tool';",
"            apiMsgs.push({ role: 'tool', tool_call_id: tc.id, name: tc.function.name, content });",
"          }",
"        } else { done = true; finalMsg = msg; }",
"      }",
"      if (finalMsg) {",
"        const all = [...newMsgs, finalMsg];",
"        setMessages(all);",
"        setChatHistory(p => p.map(c => c.id === chatId ? { ...c, messages: all, title: input.substring(0,30) } : c));",
"        if (isTTSEnabled) { const ut = new SpeechSynthesisUtterance(finalMsg.content.replace(/[*#`_]/g, '')); ut.lang = 'th-TH'; window.speechSynthesis.speak(ut); }",
"      }",
"    } catch (err) { setMessages(p => [...p, { role: 'assistant', content: 'Error: ' + err.message }]); }",
"    finally { setIsLoading(false); }",
"  };",
"",
"  const md = getMd(isDark);",
"  const D = isDark;",
"",
"  return (",
"    <div className={'fixed inset-0 z-[9999] flex overflow-hidden ' + (D ? 'bg-[#212121]' : 'bg-white')} style={{ fontFamily: 'Inter, sans-serif' }}>",
"      <style>{`@keyframes bounce{0%,80%,100%{transform:translateY(0)}40%{transform:translateY(-5px)}} .gpt-sb::-webkit-scrollbar{width:5px}.gpt-sb::-webkit-scrollbar-thumb{background:${D?'#444':'#ccc'};border-radius:10px}`}</style>",
"",
"      {/* Sidebar */}",
"      <div className={'flex-col overflow-hidden border-r transition-all duration-300 ' + (D?'bg-[#171717] border-white/10 text-white':'bg-[#f7f7f8] border-gray-200 text-gray-800') + ' ' + (isSidebarOpen?'w-64 flex':'w-0 hidden')}>",
"        <div className='p-3'>",
"          <button onClick={startNewChat} className={'w-full flex items-center gap-2 p-2.5 rounded-lg border text-sm ' + (D?'border-white/20 hover:bg-white/10 text-white':'border-gray-300 hover:bg-gray-200 text-gray-800')}>",
"            <Plus size={16}/> New chat",
"          </button>",
"        </div>",
"        <div className='flex-1 overflow-y-auto px-2 gpt-sb'>",
"          {chatHistory.map(c => (",
"            <div key={c.id} onClick={() => loadChat(c)} className={'flex items-center justify-between p-2.5 rounded-lg cursor-pointer text-sm mb-0.5 ' + (currentChatId===c.id?(D?'bg-white/10':'bg-gray-200'):(D?'hover:bg-white/5 text-white/60':'hover:bg-gray-200 text-gray-500'))}>",
"              <div className='flex items-center gap-2 overflow-hidden'><MessageSquare size={13}/><span className='truncate'>{c.title}</span></div>",
"              <button onClick={e => deleteChat(e, c.id)} className='opacity-40 hover:opacity-100 hover:text-red-400 p-1'><Trash2 size={12}/></button>",
"            </div>",
"          ))}",
"        </div>",
"      </div>",
"",
"      {/* Main */}",
"      <div className='flex-1 flex flex-col min-w-0'>",
"        {/* Header */}",
"        <div className={'flex items-center justify-between px-4 py-3 border-b ' + (D?'border-white/10':'border-gray-200')}>",
"          <div className='flex items-center gap-3'>",
"            <button onClick={() => setIsSidebarOpen(p=>!p)} className={'p-2 rounded-lg ' + (D?'hover:bg-white/10 text-white/60':'hover:bg-gray-100 text-gray-500')}><LayoutDashboard size={18}/></button>",
"            <div className='flex items-center gap-2'>",
"              <div className='w-8 h-8 rounded-lg bg-gradient-to-br from-blue-500 to-violet-600 flex items-center justify-center'><Sparkles size={16} className='text-white'/></div>",
"              <div>",
"                <div className={'text-sm font-semibold ' + (D?'text-white':'text-gray-900')}>{BOT_NAME}</div>",
"                <div className={'text-[10px] ' + (D?'text-white/40':'text-gray-400')}>{isLoading?'Thinking...':'Inventory AI'}</div>",
"              </div>",
"            </div>",
"          </div>",
"          <div className='flex items-center gap-1'>",
"            <button onClick={() => setIsDark(p=>!p)} className={'p-2 rounded-lg ' + (D?'hover:bg-white/10 text-yellow-400':'hover:bg-gray-100 text-gray-500')}>{D?<Sun size={18}/>:<Moon size={18}/>}</button>",
"            <button onClick={toggleTTS} className={'p-2 rounded-lg ' + (D?'hover:bg-white/10 text-white/50':'hover:bg-gray-100 text-gray-500')}>{isTTSEnabled?<Volume2 size={18}/>:<VolumeX size={18}/>}</button>",
"            <button onClick={onBack} className={'p-2 rounded-lg ' + (D?'hover:bg-white/10 text-white/40':'hover:bg-gray-100 text-gray-400')}><X size={18}/></button>",
"          </div>",
"        </div>",
"",
"        {/* Messages */}",
"        <div className='flex-1 overflow-y-auto gpt-sb'>",
"          {messages.length === 0 && (",
"            <div className='flex flex-col items-center justify-center h-full gap-4'>",
"              <Sparkles size={48} className={'opacity-10 ' + (D?'text-blue-400':'text-gray-400')}/>",
"              <p className={'text-base font-medium ' + (D?'text-white/30':'text-gray-300')}>How can I help you today?</p>",
"            </div>",
"          )}",
"          {messages.map((m, i) => (",
"            <div key={i} className={'px-4 py-6 border-b ' + (m.role==='assistant'?(D?'bg-white/[0.02] border-white/5':'bg-gray-50 border-gray-100'):'border-transparent')}>",
"              <div className='max-w-3xl mx-auto flex gap-4'>",
"                <div className={'w-8 h-8 rounded-lg shrink-0 flex items-center justify-center ' + (m.role==='user'?'bg-slate-600':'bg-gradient-to-br from-blue-500 to-violet-600')}>",
"                  {m.role==='user'?<User size={15} className='text-white'/>:<Sparkles size={15} className='text-white'/>}",
"                </div>",
"                <div className={'flex-1 text-sm leading-7 ' + (D?'text-white/90':'text-gray-800')}>",
"                  <ReactMarkdown remarkPlugins={[remarkGfm]} components={md}>{m.content}</ReactMarkdown>",
"                  {m.hasFile && <div className={'mt-3 p-2 rounded-lg border flex items-center gap-2 text-xs ' + (D?'bg-white/5 border-white/10 text-white/50':'bg-gray-50 border-gray-200 text-gray-400')}><FileText size={13}/>{m.fileName}</div>}",
"                </div>",
"              </div>",
"            </div>",
"          ))}",
"          {isLoading && (",
"            <div className={'px-4 py-6 border-b ' + (D?'bg-white/[0.02] border-white/5':'bg-gray-50 border-gray-100')}>",
"              <div className='max-w-3xl mx-auto flex gap-4'>",
"                <div className='w-8 h-8 rounded-lg bg-gradient-to-br from-blue-500 to-violet-600 flex items-center justify-center'><Sparkles size={15} className='text-white'/></div>",
"                <div className='flex items-center gap-1.5 mt-3'>",
"                  {[0,1,2].map(i => <span key={i} className={'w-1.5 h-1.5 rounded-full inline-block ' + (D?'bg-white/30':'bg-gray-400')} style={{animation:'bounce 1.2s ease-in-out '+(i*0.2)+'s infinite'}}/>)}",
"                </div>",
"              </div>",
"            </div>",
"          )}",
"          <div ref={messagesEndRef}/>",
"        </div>",
"",
"        {/* Input */}",
"        <div className={'px-4 pb-4 pt-3 ' + (D?'bg-[#212121]':'bg-white border-t border-gray-100')}>",
"          <div className='max-w-3xl mx-auto relative'>",
"            {attachedFile && (",
"              <div className={'absolute -top-14 left-0 flex items-center gap-2 px-3 py-2 rounded-xl border ' + (D?'bg-[#2f2f2f] border-white/10':'bg-white border-gray-200')}>",
"                {imagePreview?<img src={imagePreview} className='w-7 h-7 rounded object-cover' alt='preview'/>:<FileText size={14} className='text-blue-500'/>}",
"                <span className={'text-xs ' + (D?'text-white':'text-gray-700')}>{attachedFile.name}</span>",
"                <button onClick={() => setAttachedFile(null)} className='text-gray-400 hover:text-red-400'><X size={13}/></button>",
"              </div>",
"            )}",
"            <div className={'flex items-end gap-2 border rounded-2xl px-3 py-2 ' + (D?'bg-[#2f2f2f] border-white/10 focus-within:border-white/25':'bg-gray-100 border-gray-300 focus-within:border-blue-400')}>",
"              <button onClick={() => document.getElementById('joi-file').click()} className={'p-2 rounded-lg ' + (D?'text-white/30 hover:text-white/70':'text-gray-400 hover:text-gray-700')}><Paperclip size={18}/></button>",
"              <input id='joi-file' type='file' className='hidden' onChange={handleFileChange}/>",
"              <textarea ref={textareaRef} rows={1} value={input} onChange={e => setInput(e.target.value)} onKeyDown={e => { if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();handleSend();} }} placeholder='Message Joi...' className={'flex-1 bg-transparent border-none focus:ring-0 py-2 text-sm resize-none gpt-sb leading-6 ' + (D?'text-white placeholder:text-white/25':'text-gray-900 placeholder:text-gray-400')}/>",
"              <button onClick={handleSend} disabled={isLoading||!input.trim()} className={'p-2 rounded-xl text-sm transition-all ' + (D?'bg-white text-black hover:bg-gray-100 disabled:opacity-20':'bg-gray-900 text-white hover:bg-gray-700 disabled:opacity-20')}><Send size={16}/></button>",
"            </div>",
"            <p className={'text-center text-[10px] mt-2 ' + (D?'text-white/10':'text-gray-300')}>Read-only. Your inventory data is secure.</p>",
"          </div>",
"        </div>",
"      </div>",
"    </div>",
"  );",
"};",
"",
"export default AIChatBot;",
].join('\n');

fs.writeFileSync('src/components/ui/AIChatBot.jsx', code, { encoding: 'utf8', flag: 'w' });
console.log('SUCCESS. Lines: ' + code.split('\n').length);
