import fs from 'fs';

const code = [
  "import React, { useState, useRef, useEffect, useCallback } from 'react';",
  "import ReactMarkdown from 'react-markdown';",
  "import remarkGfm from 'remark-gfm';",
  "import {",
  "  MessageSquare, X, Send, Sparkles, LayoutDashboard,",
  "  Paperclip, FileText, Trash2, Volume2, VolumeX, Image, User,",
  "  Plus, Settings, Sun, Moon",
  "} from 'lucide-react';",
  "import { useLanguage } from '../../contexts/LanguageContext';",
  "import { readExcelFile, sheetToJSON } from '../../utils/excelProcessor';",
  "import { supabase } from '../../utils/supabaseClient';",
  "",
  "const BOT_NAME = 'Joi';",
  "const DEEPSEEK_API_KEY = import.meta.env.VITE_DEEPSEEK_API_KEY || '';",
  "const GEMINI_API_KEY = import.meta.env.VITE_GEMINI_API_KEY || '';",
  "",
  "const getMd = (dark) => ({",
  "  h1: ({children}) => <h1 className={'text-2xl font-bold mt-6 mb-4 ' + (dark?'text-white':'text-gray-900')}>{children}</h1>,",
  "  h2: ({children}) => <h2 className={'text-xl font-bold mt-5 mb-3 ' + (dark?'text-white':'text-gray-800')}>{children}</h2>,",
  "  p: ({children}) => <p className='mb-4 leading-relaxed text-[15px] opacity-90'>{children}</p>,",
  "  strong: ({children}) => <strong className={'font-semibold ' + (dark?'text-white':'text-gray-900')}>{children}</strong>,",
  "  ul: ({children}) => <ul className='list-disc pl-5 mb-4 space-y-2 opacity-90'>{children}</ul>,",
  "  ol: ({children}) => <ol className='list-decimal pl-5 mb-4 space-y-2 opacity-90'>{children}</ul>,",
  "  table: ({children}) => <div className={'overflow-x-auto my-6 rounded-2xl border ' + (dark?'border-white/10':'border-gray-200')}><table className='w-full text-sm border-collapse'>{children}</table></div>,",
  "  thead: ({children}) => <thead className={dark?'bg-white/5':'bg-gray-50'}>{children}</thead>,",
  "  th: ({children}) => <th className='px-4 py-3 text-left font-semibold opacity-60 text-xs uppercase tracking-wider'>{children}</th>,",
  "  td: ({children}) => <td className={'px-4 py-3 border-b ' + (dark?'border-white/5':'border-gray-100')}>{children}</td>,",
  "  tr: ({children}) => <tr className='transition-colors'>{children}</tr>,",
  "  code: ({inline, children}) => inline",
  "    ? <code className={'px-1.5 py-0.5 rounded text-xs font-mono ' + (dark?'bg-white/10 text-blue-300':'bg-gray-100 text-blue-600')}>{children}</code>",
  "    : <pre className={'p-5 rounded-2xl overflow-x-auto text-xs font-mono my-4 border ' + (dark?'bg-[#1e1f20] text-blue-300 border-white/10':'bg-gray-900 text-green-400')}><code>{children}</code></pre>,",
  "});",
  "",
  "const ThinkingDots = () => (",
  "  <div className='max-w-3xl mx-auto px-4 flex gap-5 py-6'>",
  "    <div className='shrink-0 mt-1'><Sparkles size={24} className='text-blue-400 animate-pulse'/></div>",
  "    <div className='flex-1 space-y-3 pt-2'>",
  "      <div className='h-2 rounded-full w-[90%] bg-blue-500/10 animate-pulse' style={{animationDuration: '2s'}}/>",
  "      <div className='h-2 rounded-full w-[70%] bg-blue-500/10 animate-pulse' style={{animationDuration: '2.5s'}}/>",
  "    </div>",
  "  </div>",
  ");",
  "",
  "const AIChatBot = ({ onBack, currentUser }) => {",
  "  const [messages, setMessages] = useState([]);",
  "  const [input, setInput] = useState('');",
  "  const [isLoading, setIsLoading] = useState(false);",
  "  const [chatHistory, setChatHistory] = useState([]);",
  "  const [currentChatId, setCurrentChatId] = useState(null);",
  "  const [isSidebarOpen, setIsSidebarOpen] = useState(true);",
  "  const [isDark, setIsDark] = useState(true);",
  "  const [attachedFile, setAttachedFile] = useState(null);",
  "  const [imagePreview, setImagePreview] = useState(null);",
  "  const [fileContent, setFileContent] = useState('');",
  "  const messagesEndRef = useRef(null);",
  "  const textareaRef = useRef(null);",
  "  const { language } = useLanguage();",
  "  const detectedLang = language === 'la' ? 'Lao' : 'Thai';",
  "",
  "  useEffect(() => {",
  "    const saved = localStorage.getItem('joah_ai_history');",
  "    if (saved) setChatHistory(JSON.parse(saved));",
  "    else startNewChat();",
  "  }, []);",
  "",
  "  useEffect(() => {",
  "    if (currentChatId && messages.length > 0) {",
  "      const u = chatHistory.map(c => c.id === currentChatId ? { ...c, messages, title: messages[1]?.content?.substring(0,30) || 'New chat' } : c);",
  "      if (!chatHistory.find(c => c.id === currentChatId)) u.push({ id: currentChatId, messages, title: 'New chat' });",
  "      setChatHistory(u);",
  "      localStorage.setItem('joah_ai_history', JSON.stringify(u));",
  "    }",
  "  }, [messages]);",
  "",
  "  const startNewChat = () => {",
  "    const id = Date.now().toString();",
  "    setCurrentChatId(id);",
  "    const name = currentUser?.name || 'ທ່ານ';",
  "    setMessages([{ role: 'assistant', content: `ສະບາຍດີ **${name}** 👋 ຂ້ອຍຊື່ **${BOT_NAME}** ຕົວຊ່ວຍ AI ຂອງ Joah Inventory. ມີຫຍັງໃຫ້ຊ່ວຍບໍ່?` }]);",
  "  };",
  "",
  "  const loadChat = (c) => { setCurrentChatId(c.id); setMessages(c.messages); };",
  "  const deleteChat = (e, id) => {",
  "    e.stopPropagation();",
  "    const u = chatHistory.filter(c => c.id !== id);",
  "    setChatHistory(u);",
  "    localStorage.setItem('joah_ai_history', JSON.stringify(u));",
  "    if (currentChatId === id) startNewChat();",
  "  };",
  "",
  "  const fetchStock = async (barcode) => {",
  "    const [{data:s},{data:d},{data:l}] = await Promise.all([",
  "      supabase.from('store_inventory').select('*').eq('barcode_no', barcode),",
  "      supabase.from('table_dc_stock').select('*').eq('barcode_no', barcode),",
  "      supabase.from('location_inventory').select('*').eq('barcode_no', barcode)",
  "    ]);",
  "    let res = `Stock for ${barcode}:\\n`;",
  "    if(s?.length) s.forEach(r => res += `- Shop ${r.branch_id}: ${r.store_qty}\\n`);",
  "    if(l?.length) l.forEach(r => res += `- Backstore ${r.branch_id}: ${r.qty}\\n`);",
  "    return res || 'No data found.';",
  "  };",
  "",
  "  const fetchDailyRequests = async () => {",
  "    const today = new Date().toISOString().split('T')[0];",
  "    const { data } = await supabase.from('store_requests').select('*').gte('created_at', today+'T00:00:00').lte('created_at', today+'T23:59:59');",
  "    if(!data?.length) return 'No requests today.';",
  "    let out = `Today\\'s Requests:\\n`;",
  "    data.forEach(r => out += `- ${r.branch_id}: ${r.product_name} x ${r.qty} (${r.status})\\n`);",
  "    return out;",
  "  };",
  "",
  "  const handleSend = async () => {",
  "    const inputMsg = input.trim();",
  "    if (!inputMsg && !attachedFile) return;",
  "    const userMsg = { role: 'user', content: inputMsg };",
  "    setMessages(prev => [...prev, userMsg]);",
  "    setInput(''); setIsLoading(true);",
  "",
  "    try {",
  "      const systemPrompt = `You are ${BOT_NAME}, a smart AI for Joah Inventory. TOOL DATA IS LAW. Never hallucinate. Reply in ${detectedLang}.`;",
  "      const apiMessages = [{ role: 'system', content: systemPrompt }, ...messages.slice(-10), userMsg];",
  "      ",
  "      const tools = [",
  "        { type: 'function', function: { name: 'check_stock', description: 'Get stock balance', parameters: { type: 'object', properties: { barcode: { type: 'string' } }, required: ['barcode'] } } },",
  "        { type: 'function', function: { name: 'get_daily_requests', description: 'Get today\\'s requests' } }",
  "      ];",
  "",
  "      let done = false, finalAiMsg = null;",
  "      let iters = 0;",
  "      while(!done && iters < 5) {",
  "        iters++;",
  "        const res = await fetch('https://api.deepseek.com/v1/chat/completions', {",
  "          method: 'POST', headers: { 'Content-Type': 'application/json', 'Authorization': `Bearer ${DEEPSEEK_API_KEY}` },",
  "          body: JSON.stringify({ model: 'deepseek-chat', messages: apiMessages, tools, tool_choice: 'auto' })",
  "        });",
  "        const d = await res.json();",
  "        const msg = d.choices[0].message;",
  "        apiMessages.push(msg);",
  "        if (msg.tool_calls) {",
  "          for (const tc of msg.tool_calls) {",
  "            const args = JSON.parse(tc.function.arguments || '{}');",
  "            const content = tc.function.name === 'check_stock' ? await fetchStock(args.barcode) : await fetchDailyRequests();",
  "            apiMessages.push({ role: 'tool', tool_call_id: tc.id, name: tc.function.name, content });",
  "          }",
  "        } else { done = true; finalAiMsg = msg; }",
  "      }",
  "      if (finalAiMsg) setMessages(prev => [...prev, finalAiMsg]);",
  "    } catch (err) { setMessages(prev => [...prev, { role: 'assistant', content: 'Error: ' + err.message }]); }",
  "    finally { setIsLoading(false); }",
  "  };",
  "",
  "  const D = isDark; const md = getMd(D);",
  "  return (",
  "    <div className={'fixed inset-0 z-[9999] flex overflow-hidden ' + (D ? 'bg-[#131314] text-[#e3e3e3]' : 'bg-white text-gray-800')} style={{ fontFamily: 'Inter, system-ui, sans-serif' }}>",
  "      <style>{`.gemini-sb::-webkit-scrollbar { width: 4px; } .gemini-sb::-webkit-scrollbar-thumb { background: ${D?'#333':'#ddd'}; border-radius: 10px; }`}</style>",
  "      ",
  "      <div className={'transition-all duration-300 flex flex-col border-r ' + (D?'bg-[#1e1f20] border-white/5':'bg-[#f0f4f9] border-gray-200') + ' ' + (isSidebarOpen?'w-64':'w-0 opacity-0')}>",
  "        <div className='p-4'><button onClick={startNewChat} className={'flex items-center gap-3 px-4 py-3 rounded-full ' + (D?'bg-[#131314] hover:bg-[#2a2b2c] text-white/70':'bg-white hover:bg-gray-100 shadow-sm text-gray-700')}><Plus size={20}/><span className='text-sm font-medium'>New Chat</span></button></div>",
  "        <div className='flex-1 overflow-y-auto px-2 gemini-sb'>",
  "          <div className='text-[11px] font-bold px-4 mb-2 opacity-40 uppercase tracking-widest'>Recent</div>",
  "          {chatHistory.map(c => (",
  "            <div key={c.id} onClick={() => loadChat(c)} className={'flex items-center justify-between px-4 py-2.5 rounded-full cursor-pointer text-sm mb-1 group transition-all ' + (currentChatId===c.id?(D?'bg-[#131314] text-white':'bg-[#d3e3fd] text-[#041e49]'):(D?'hover:bg-[#131314] text-white/70':'hover:bg-gray-200 text-gray-600'))}>",
  "              <div className='flex items-center gap-3 overflow-hidden'><MessageSquare size={16}/><span className='truncate'>{c.title}</span></div>",
  "              <button onClick={e => deleteChat(e, c.id)} className='opacity-0 group-hover:opacity-60 hover:text-red-400'><Trash2 size={14}/></button>",
  "            </div>",
  "          ))}",
  "        </div>",
  "      </div>",
  "",
  "      <div className='flex-1 flex flex-col min-w-0 relative'>",
  "        <div className='flex items-center justify-between px-4 py-3'>",
  "          <div className='flex items-center gap-2'><button onClick={() => setIsSidebarOpen(!isSidebarOpen)} className={'p-2.5 rounded-full ' + (D?'hover:bg-white/5 text-white/70':'hover:bg-gray-100 text-gray-600')}><LayoutDashboard size={20}/></button><span className='font-semibold text-lg'>Joi AI Agent</span></div>",
  "          <div className='flex items-center gap-2'><button onClick={() => setIsDark(!D)} className={'p-2.5 rounded-full ' + (D?'text-yellow-400 hover:bg-white/5':'text-gray-500 hover:bg-gray-100')}>{D?<Sun size={20}/>:<Moon size={20}/>}</button><button onClick={onBack} className={'p-2.5 rounded-full ' + (D?'text-white/40 hover:bg-white/5':'text-gray-400 hover:bg-gray-100')}><X size={20}/></button></div>",
  "        </div>",
  "",
  "        <div className='flex-1 overflow-y-auto gemini-sb pt-4 pb-32'>",
  "          {messages.length === 1 && (",
  "            <div className='max-w-3xl mx-auto px-4 mt-20'><h1 className='text-5xl font-medium mb-2 bg-gradient-to-r from-blue-400 via-purple-400 to-red-400 bg-clip-text text-transparent'>Hello, I\\'m Joi</h1><p className='text-3xl font-medium opacity-20'>I am your smart inventory assistant.</p></div>",
  "          )}",
  "          {messages.map((m, i) => (",
  "            <div key={i} className='w-full py-6'><div className='max-w-3xl mx-auto px-4 flex gap-5'><div className={'shrink-0 mt-1 ' + (m.role==='user'?'order-last':'')}>{m.role==='user' ? <div className='w-8 h-8 rounded-full bg-slate-500 flex items-center justify-center'><User size={18} color='white'/></div> : <div className='w-8 h-8 flex items-center justify-center'><Sparkles size={24} className='text-blue-400'/></div>}</div><div className={'flex-1 text-[15px] leading-relaxed ' + (m.role==='user'?'text-right':'')}><div className={m.role==='user' ? (D?'bg-[#1e1f20] px-5 py-3 rounded-3xl inline-block text-left':'bg-[#f0f4f9] px-5 py-3 rounded-3xl inline-block text-left') : ''}><ReactMarkdown remarkPlugins={[remarkGfm]} components={md}>{m.content}</ReactMarkdown></div></div></div></div>",
  "          ))}",
  "          {isLoading && <ThinkingDots />}",
  "          <div ref={messagesEndRef} />",
  "        </div>",
  "",
  "        <div className={'absolute bottom-0 left-0 right-0 px-4 pb-6 pt-2 ' + (D?'bg-gradient-to-t from-[#131314] via-[#131314] to-transparent':'bg-gradient-to-t from-white via-white to-transparent')}>",
  "          <div className='max-w-3xl mx-auto relative'><div className={'flex items-end gap-2 px-6 py-3 rounded-full border transition-all duration-300 ' + (D?'bg-[#1e1f20] border-transparent focus-within:bg-[#28292a] shadow-xl':'bg-[#f0f4f9] border-transparent focus-within:bg-white focus-within:shadow-lg')}><button className={'p-2 rounded-full ' + (D?'text-white/60 hover:bg-white/5':'text-gray-500 hover:bg-gray-200')}><Paperclip size={20}/></button><textarea ref={textareaRef} rows={1} value={input} onChange={e => setInput(e.target.value)} onKeyDown={e => { if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();handleSend();} }} placeholder='Ask about stock or requests...' className={'flex-1 bg-transparent border-none focus:ring-0 py-2 text-base resize-none ' + (D?'text-white placeholder:text-white/40':'text-gray-900 placeholder:text-gray-500')}/><button onClick={handleSend} disabled={isLoading||!input.trim()} className={'p-2 rounded-full ' + (D?'text-blue-400 hover:bg-blue-400/10':'text-blue-600 hover:bg-blue-50')}><Send size={20}/></button></div><p className={'text-center text-[10px] mt-3 opacity-30 tracking-tight'}>Joi accesses live warehouse data. Data is accurate as of today.</p></div>",
  "        </div>",
  "      </div>",
  "    </div>",
  "  );",
  "};",
  "",
  "export default AIChatBot;"
].join('\n');

fs.writeFileSync('src/components/ui/AIChatBot.jsx', code, { encoding: 'utf8', flag: 'w' });
console.log('SUCCESS. Smart Gemini Joi UI Applied.');
